//moving sound effect is downloaded from https://pixabay.com/sound-effects/robot-moving-driving-takeoff-motor-sound-12-different-ses-109030/ and then trimmed

//collision, death and eating sound effect are generated by https://sfxr.me/

//bgmForGhostNormal is created with chrome music lab by myself: https://musiclab.chromeexperiments.com/Song-Maker/song/6300473330237440

//bgmForGhostDead is created with chrome music lab by myself: https://musiclab.chromeexperiments.com/Song-Maker/song/6023726449819648

//introBgm is created with chrome music lab by myself: https://musiclab.chromeexperiments.com/Song-Maker/song/5501566765498368

//bgmForGhostScared is created with chrome music lab by myself: https://musiclab.chromeexperiments.com/Song-Maker/song/6739333088542720s